services:
  bot-saisie-sahp:
    image: ghcr.io/math49/bot_saisie_sahp:latest
    container_name: saisie-sahp
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MONGO_URI: ${MONGO_URI}
    networks:
      - sahp-network

networks:
  sahp-network:
    driver: bridge